## 3.4 3層ニューラルネットワークの実装

1層目のニューロン $x_1$ から $a_1^{(1)}$ への伝播は次式で表される。
（重みと入力値の総和にバイアス値を足したもの）

\begin{align}
a_1^{(1)} = b_1^{(1)} + \sum_{n=1}^{N} w_{1n}^{(1)}x_n
\end{align}

線形変換を用いて表現すると1層目の伝播は次式のようになる。

\begin{align}
{\bf A}^{(1)} = {\bf x}{\bf W}^{(1)} + {\bf B}^{(1)}
\end{align}

In [1]:
# numpy を使って実装する
import numpy as np
# 入力ベクトル
x  = np.array([1.0, 0.5])
# 重み行列
W1 = np.array([[0.1, 0.3, 0.5],
               [0.2, 0.4, 0.6]])
# バイアスベクトル
B1 = np.array([0.1, 0.2, 0.3])
# 第1層の出力ベクトル
A1 = np.dot(x, W1) + B1
print(A1)

[ 0.3  0.7  1.1]


In [2]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

# 第1層の出力ベクトル(活性化関数: シグモイド)
Z1 = sigmoid(A1)

print('### 変換前 ###')
print(A1)
print('### 変換後 ###')
print(Z1)

### 変換前 ###
[ 0.3  0.7  1.1]
### 変換後 ###
[ 0.57444252  0.66818777  0.75026011]


In [3]:
# 1層目 -> 2層目
# 1層目のノード数は3, 2層目のノード数は2なので
# 重み行列は 3 x 2
W2 = np.array([[0.1, 0.4],
               [0.2, 0.5],
               [0.3, 0.6]])
# バイアスベクトル
B2 = np.array([0.1, 0.2])
# 第2層の出力ベクトル
A2 = np.dot(Z1, W2) + B2
# 第2層の出力ベクトル(変換後)
Z2 = sigmoid(A2)

print('### 変換前 ###')
print(A2)
print('### 変換後 ###')
print(Z2)

### 変換前 ###
[ 0.51615984  1.21402696]
### 変換後 ###
[ 0.62624937  0.7710107 ]


In [4]:
# 2層目 -> 出力層
# 活性化関数: 恒等写像
def identity_function(x):
    return x

# 重みベクトル
W3 = np.array([[0.1, 0.3],
               [0.2, 0.4]])
# バイアスベクトル
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
# 出力層
Y  = identity_function(A3)
print(Y)

[ 0.31682708  0.69627909]


In [5]:
# 実装まとめ
def init_networt():
    return {
        'W1': np.array([[0.1, 0.3, 0.5],
                        [0.2, 0.4, 0.6]]),
        'b1': np.array([0.1, 0.2, 0.3]),
        'W2': np.array([[0.1, 0.4],
                        [0.2, 0.5],
                        [0.3, 0.6]]),
        'b2': np.array([0.1, 0.2]),
        'W3': np.array([[0.1, 0.3],
                        [0.2, 0.4]]),
        'b3': np.array([0.1, 0.2])
    }

def forward(network, input_vector):
    W1 = network['W1']
    W2 = network['W2']
    W3 = network['W3']
    b1 = network['b1']
    b2 = network['b2']
    b3 = network['b3']
    
    z1 = sigmoid(np.dot(x , W1) + b1)
    z2 = sigmoid(np.dot(z1, W2) + b2)
    
    return identity_function(np.dot(z2, W3) + b3)

network = init_networt()
input_vector  = np.array([1.0, 0.5])
output_vector = forward(network, input_vector)
print(output_vector)

[ 0.31682708  0.69627909]
