### 3.3.2 行列演算（numpy）

In [1]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
print(A)
A.shape

[[1 2]
 [3 4]]


(2, 2)

In [2]:
B = np.array([[5, 6], [7, 8]])
print(B)
B.shape

[[5 6]
 [7 8]]


(2, 2)

In [3]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [4]:
# 可換かどうかは保証されない (ドット積なので当たり前)
np.dot(B, A)

array([[23, 34],
       [31, 46]])

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape)
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B.shape)
np.dot(A, B)

(2, 3)
(3, 2)


array([[22, 28],
       [49, 64]])

In [6]:
C = np.array([[1, 2], [3, 4]])
print(C)
C.shape

[[1 2]
 [3 4]]


(2, 2)

In [7]:
# 演算子の右側の行列と列数と左側の行数が一致していないと例外が発生する
print(A.shape)
print(C.shape)
np.dot(A, C)

(2, 3)
(2, 2)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [8]:
print(A)
print(B)
np.dot(A, B)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


array([[22, 28],
       [49, 64]])

### 3.3.3 ニューラルネットにおけるドット積

In [9]:
input_vector = np.array([1, 2])
input_vector.shape

(2,)

In [10]:
weight_matrix = np.array([[1, 3, 5],  # x1 -> yn に対する重み
                          [2, 4, 6]]) # x2 -> yn に対する重み

In [11]:
# 単層のネットワークにおける出力層の計算は 1 回のドット積で表現できる
output_vector = np.dot(input_vector, weight_matrix)
print(output_vector)

[ 5 11 17]
